@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package mrp_v2.configurablerecipeslibrary.item.crafting;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;