modLoader="javafml"
loaderVersion="[${majorForgeVersion},)"
license="All rights reserved"
[[mods]]
	modId="${modId}"
	version="${version}"
	displayName="Configurable Recipes Library"
	logoFile="ConfigurableRecipesLibraryLogo.png"
	updateJSONURL="https://raw.githubusercontent.com/mrp-v2/ModUpdateFiles/master/ConfigurableRecipesLibrary.json"
	issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/configurable-recipes-library/issues"
	displayURL="https://minecraft.curseforge.com/projects/configurable-recipes-library"
	authors="mrp_v2"
	description='''Adds recipe types that can change depending on certain values.'''
[[dependencies.${modId}]]
    modId="forge"
    mandatory=true
    versionRange="[${majorForgeVersion},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modId}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcVersion}]"
    ordering="NONE"
    side="BOTH"