modLoader="javafml"
loaderVersion="[33,)"
license="All rights reserved"
[[mods]]
	modId="configurablerecipeslibrary"
	version="${version}"
	displayName="Configurable Recipes Library"
	logoFile="ConfigurableRecipesLibraryLogo.png"
	updateJSONURL="https://raw.githubusercontent.com/mrp-v2/ModUpdateFiles/master/ConfigurableRecipesLibrary.json"
	issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/configurable-recipes-library/issues"
	displayURL="https://minecraft.curseforge.com/projects/configurable-recipes-library"
	authors="mrp_v2"
	description='''Adds recipe types that can change depending on certain values.'''
[[dependencies.configurablerecipeslibrary]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.configurablerecipeslibrary]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"