@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package mrp_v2.configurablerecipeslibrary;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;