@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package mrp_v2.configurablerecipeslibrary.datagen;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;